### ISSUE TITLE
Any plans to add stats ? 

### ISSUE THREAD

**Issue by rkscodes** [ivoronin/TomatoBar#45] opened 2023-01-06 10:35 UTC
It would be really cool to know how many pomodora was done on some particular day. Is it something this app will consider ?

**Comment by becauseim** [comment] 2023-01-24 08:33
yes, add sprints, please
it is convenient and functional

**Comment by sn0n** [comment] 2023-05-05 07:34
Definitely something that would be useful, but could be a bit of work..

**Comment by yoghurtdewdew** [comment] 2023-09-02 03:26
I want a log to check how many 🍅 a day/week/month. Or just show me when I start & end a 🍅.

**Comment by ivoronin** [comment] 2023-09-05 13:08
Duplicate of #46

**Closed by ivoronin** 2023-09-05 13:08 UTC
